urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

from www.sitemap import sitemaps

urlpatterns = patterns('',
    (r'^', include('frankarturo.www.urls')),
    (r'^contact/', include('frankarturo.contact_form.urls')),
    (r'^mylovelymontreal/', include('frankarturo.mylovelymontreal.urls')),

    (r'^admin/', include(admin.site.urls)),
    
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT})
    )

www/urls.py
from django.conf.urls.defaults import *

from contact_form.forms import ContactForm

urlpatterns = patterns('www.views',
    url(r'^$', 'index', name="www_index"),
    url(r'^contact-us/$', 'contact_form', name='www_contact_form'),
)

# This is for layout-demonstration purposes. After you saw it, you can delete and implement urls in a proper manner.
urlpatterns += patterns('django.views.generic.simple',
    url(r'^obesity/$', 'direct_to_template', {'template': 'www/obesity.html'}, name="www_obesity"),
    url(r'^team/$', 'direct_to_template', {'template': 'www/team.html'}, name="www_team"),
    
    url(r'^photogallery/$', 'direct_to_template', {'template' : 'www/photogallery.html'}, name="www_photogallery"),
    url(r'^photogallery/capella$', 'direct_to_template', {'template' : 'www/capella.html'}, name="www_capella"),
    url(r'^photogallery/sleeve/$', 'direct_to_template', {'template' : 'www/sleeve.html'}, name="www_sleeve"),
    url(r'^photogallery/apendicite/$', 'direct_to_template', {'template' : 'www/apendicite.html'}, name="www_apendicite"),
    
    url(r'^articles/$', 'direct_to_template', {'template' : 'www/articles.html'}, name="www_articles"),
    url(r'^articles/article1/$', 'direct_to_template', {'template' : 'www/article1.html'}, name="www_article1"),
    url(r'^articles/article2/$', 'direct_to_template', {'template' : 'www/article2.html'}, name="www_article2"),
    url(r'^articles/article3/$', 'direct_to_template', {'template' : 'www/article3.html'}, name="www_article3"),
    url(r'^articles/article4/$', 'direct_to_template', {'template' : 'www/article4.html'}, name="www_article4"),
    url(r'^articles/obesitysearch/$', 'direct_to_template', {'template' : 'www/obesity_search.html'}, name="www_obesitysearch"),
)

urlpatterns += patterns('www.views',
    url(r'^bmi/$', 'calculate_bmi', name="www_bmi"),
)

urlpatterns += patterns('ajax_validation.views',
    url(r'^form/contact/validate/$', 'validate', {'form_class': ContactForm, 'callback' : lambda request, *args, **kwargs: {'request' : request}}, 'contact_form_validate'),
)

www/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.conf import settings

class BMICalculateForm(forms.Form):
    weight = forms.FloatField()
    height = forms.FloatField(help_text=_('height in centimeters. use 170 if you own 1.70 meters.'))

    def calculate(self):
        bmi = ''
        if 'weight' in self.cleaned_data and 'height' in self.cleaned_data:
            bmi = self.cleaned_data['weight'] / (self.cleaned_data['height'] ** 2)
        return bmi

www/views.py
from django.http import HttpResponse
from annoying.decorators import render_to
from django.views.decorators.http import require_POST

from contact_form.forms import ContactForm
from www.forms import BMICalculateForm

@render_to('www/index.html')
def index(request):
    c = {}
    
    #section = Section.menu.filter(url_name='articles')
    #c['last_articles'] = Page.index.filter(section=section)[:5]
    
    return c

@render_to('www/bmi.html')
def calculate_bmi(request):
    c = {}
    if request.method == 'POST':
        form = BMICalculateForm(request.POST)
        if form.is_bound and form.is_valid():
            c['bmi'] = form.calculate()
    else:
        form = BMICalculateForm()
        
    c['form'] = form
    return c

@require_POST
def contact_form(request, form_class=ContactForm, fail_silently=False):
    form = form_class(data=request.POST, files=request.FILES, request=request)
    if form.is_valid():
        form.save(fail_silently=fail_silently)
        return HttpResponse('true')
    
    return HttpResponse('false')

templates/www/apendicite.html
{% extends "www/base.html" %}
{% load i18n %}

{% block body_class %}photogallery{% endblock %}

{% block extra_head %}
	
	<style type="text/css">
		p.blocktext {
			margin-left: auto;
			margin-right: auto;
		}
		img {
			border: none;
		}
		 
		/* ---------- gallery styles start here ----------------------- */
		.gallery {
			list-style: none;
			margin: 0;
			padding: 0;
		}
		.gallery li {
			padding: 10px;
			margin: 0;
			
			position: relative;
			
		}
		.gallery li:hover img {
			border-color: #000;
		}
		.gallery img {
			background: #fff;
			border: solid 1px #888;
			padding: 5px;
			width: 360px;
			height: 260px;
		}
		.gallery em {
			background: #fff url(images/grey-gradient.gif) repeat-y;
			color: #000;
			font-style: normal;
			padding: 2px 10px;
			display: block;
			position: absolute;
			top: 110px;
			left: 180px;
			border: 1px solid #999;
			border-left-color: #888;
		}
		.gallery a {
			text-decoration: none;
		}
		.gallery a:hover em {
			background: #ffdb01 url(images/orange-gradient.gif) repeat-y;
			border-color: #c25b08;
		}
	</style> 
{% endblock %}

{% block content %}
    <div id="content">
		<h1>Apendicectomia Laparoscópica</h1>
		<br/>
		<div>
			A apendicite aguda é uma doença freqüente
			que acomete em sua maioria homens com
			uma idade média ao redor de 20 anos. O
			seu tratamento é cirúrgico e está bem estabelecido
			em sua abordagem convencional.
			O surgimento e o desenvolvimento da videolaparoscopia abriu uma
			nova opção para a abordagem  cirúrgica dessa
			patologia, permitindo uma abordagem minimamente
			invasiva com todas as vantagens dessa técnica.
		</div>
		
		</br>
		</br>
		<h1>Cirurgia convencional</h1>
		</br>
		<div class="dropshadow1">
			<p>Veja exemplos de como fica a cicatriz deformadora da cirurgia convencional.</p>
			<ul class="gallery"> 
				<li><a href="#"><em>Cicatriz</em><img src="{{ MEDIA_URL }}img/apendicite/apendicite-conv1.jpg" alt="Cicatriz da cirurgia convencional" /></a></li>
				<li><a href="#"><em>Sequela</em><img src="{{ MEDIA_URL }}img/apendicite/apendicite-conv2.jpg" alt="Cicatriz da cirurgia convencional" /></a></li>
			</ul>
		</div>
		
		</br>
		</br>
		<h1>Inovadora Cirurgia</h1>
		</br>
		<div class="dropshadow1">
			<p>
				O Dr. Frank utiliza a inovadora técnica de apendicectomia laparoscópica.
				Veja como o paciente praticamente não apresenta cicatriz.
			</p>
			<p>
				Entre em <a alt="contato" href="/contact/">contato</a> para saber mais detalhes.
			</p>
			<ul class="gallery"> 
				<li><a href="#"><em style='left: 215px; top: 55px'>No dia da cirurgia</em><img src="{{ MEDIA_URL }}img/apendicite/nova_cirurgia1.jpg" alt="No dia da cirurgia" /></a></li>
				<li><a href="#"><em style='left: 215px; top: 55px'>Uma semana depois</em><img src="{{ MEDIA_URL }}img/apendicite/nova_cirurgia2.jpg" alt="Uma semana depois" /></a></li>
				<li><a href="#"><em style='left: 250px; top: 90px'>Não aparece vestido</em><img src="{{ MEDIA_URL }}img/apendicite/nova_cirurgia3.jpg" alt="Não aparece vestido" /></a></li>
			</ul>
		</div>
		<div class="blocktext">
			Marque uma <a alt="contato" href="/contact/">consulta</a> já.
		</div>
	</div>
	<script>
		// Load the classic theme
		Galleria.loadTheme('../../static/js/gallery/galleria.classic.js');
		// Initialize Galleria
		$('#galleria').galleria();
    </script>
{% endblock %}

templates/www/article1.html
{% extends "www/base.html" %}

{% block body_class %}articles{% endblock %}
{% block content %}
    <h1>Fazer dieta não reduz número de células de gordura, diz estudo</h1>
    <br/>
    <br/>
    <p align="justify"><div class="storytext">
<strong>Uma pesquisa realizada por especialistas suecos aponta que fazer dieta n&atilde;o diminui o n&uacute;mero de c&eacute;lulas de gordura do corpo
humano. </strong>

</div>
<p class="storytext">
Os especialistas, da Universidade 
Karolinska, dizem que a quantidade de c&eacute;lulas de gordura &ndash; adip&oacute;citos &ndash; &eacute;
definida durante
a adolesc&ecirc;ncia e permanece invari&aacute;vel pelo resto da 
vida, mesmo que a pessoa venha a desenvolver obesidade no futuro.
</p>
<p class="storytext">
Os pesquisadores fizeram uma 
experi&ecirc;ncia com centenas de crian&ccedil;as, adolescentes e adultos e 
descobriram que as c&eacute;lulas de
gordura se multiplicavam durante a inf&acirc;ncia, mas que 
uma vez atingida a idade adulta, o n&uacute;mero continuava o mesmo.

</p>
<p class="storytext">
<!-- end_story -->Durante os testes, eles retiraram amostras de gordura de alguns pacientes que se preparavam para se submeter &agrave; cirurgia de
redu&ccedil;&atilde;o do est&ocirc;mago, um dos &uacute;ltimos recursos utilizados pela medicina moderna na luta contra a obesidade. 
</p>
<p class="storytext">
Depois que os pacientes emagreceram, os cientistas retiraram uma nova amostra de gordura para averig&uuml;ar se a quantidade de
adip&oacute;citos havia reduzido. 
</p>
<p class="storytext">
Eles perceberam, ent&atilde;o, que as c&eacute;lulas de gordura n&atilde;o haviam diminu&iacute;do em quantidade, mas no tamanho.

</p>
<p class="storytext">
Na avalia&ccedil;&atilde;o do coordenador da pesquisa, Kirsty Spalding, o estudo representa uma m&aacute; not&iacute;cia para quem vive fazendo dietas.
</p>
<p class="storytext">
&ldquo;Isso explica por que &eacute; t&atilde;o dif&iacute;cil perder peso e manter os quilos a menos, porque as c&eacute;lulas de gordura n&atilde;o est&atilde;o indo a
lugar nenhum. Elas ficam ali, pedindo mais comida&rdquo;, explicou ele.

</p>
Os resultados da pesquisa foram publicados na revista <em>Nature</em>.
</p>
    
{% endblock %}

templates/www/article2.html
{% extends "www/base.html" %}

{% block body_class %}articles{% endblock %}
{% block content %}
<h1>Metade da população mundial 'está obesa ou acima do peso'</h1>
<br/>
<br/>

<p align="justify"><div class="storytext">
<strong>Mais de metade da popula&ccedil;&atilde;o mundial est&aacute; obesa
ou acima do peso, apontou uma pesquisa global publicada nesta 
ter&ccedil;a-feira na revista cient&iacute;fica americana <em>Circulation Journal</em>.</strong>

</div>
<p class="storytext">
O
estudo, que analisou dados de 182.970 pessoas de 63 pa&iacute;ses nos cinco 
continentes, mostrou que 50% das mulheres e 60% dos homens analisados 
est&atilde;o acima do peso ou obesos.
</p>
<p class="storytext">
Ao considerar 
apenas os dados sobre obesidade, o levantamento revelou que um quase um 
quarto dos homens (24%) e 27% das mulheres est&atilde;o obesos.
</p>
<p class="storytext">
<!-- end_story -->Os
cientistas, liderados pelo m&eacute;dico Berverley Balkau, do Instituto 
Nacional de Sa&uacute;de e Pesquisas M&eacute;dicas da Fran&ccedil;a, utilizaram o &Iacute;ndice de 
Massa Corporal (IMC) para avaliar o grau de obesidade dos volunt&aacute;rios. 

</p>
<p class="storytext">
O
IMC &eacute; um padr&atilde;o internacional e &eacute; calculado dividindo-se o peso pela 
altura ao quadrado. Pessoas com IMC entre 18 e 24 est&atilde;o dentro do peso, 
as que se enquadram entre 25 e 30 est&atilde;o acima, e as que ultrapassaram o 
&iacute;ndice de 30 s&atilde;o consideradas obesas.
</p>
<p class="storytext">
<strong>Doen&ccedil;as associadas</strong>

</p>
<p class="storytext">
O
pa&iacute;s com maior n&uacute;mero de obesos - entre os analisados - foi o Canad&aacute; 
(36%) e as regi&otilde;es com os menores &iacute;ndices de obesidade foram o leste e o
sul asi&aacute;tico (7%). Os Estados Unidos n&atilde;o foram analisados na pesquisa. 
</p>
<p class="storytext">
A &Aacute;frica do Sul (33%) e os pa&iacute;ses do Oriente M&eacute;dio (36%) tamb&eacute;m apresentaram grandes &iacute;ndices de obesidade. 

</p>
<p class="storytext">
Na Am&eacute;rica Latina, os pesquisadores identificaram que 29% dos pesquisados estavam obesos.
</p>
<p class="storytext">
&ldquo;Os
resultados da pesquisa mostram que o excesso de peso est&aacute; virando uma 
pandemia, com mais da metade da popula&ccedil;&atilde;o acima do peso ou obesa&rdquo;, disse
Berverley Balkau. 
</p>
<p class="storytext">
O levantamento ainda 
pesquisou como a obesidade est&aacute; afetando a sa&uacute;de das pessoas e revelou 
que entre os entrevistados, 16% dos homens 13% das mulheres apresentavam
doen&ccedil;as cardiovasculares e que a diabetes atingia 13% dos homens e 11% 
das mulheres em todas as regi&otilde;es pesquisadas.

</p>
<p class="storytext">
&ldquo;A
obesidade est&aacute; associada diretamente ao aumento do risco de doen&ccedil;as 
cardiovasculares e diabetes e se tornou um grande problema de sa&uacute;de 
p&uacute;blica que amea&ccedil;a boa parte da popula&ccedil;&atilde;o e sobrecarrega os servi&ccedil;os 
p&uacute;blicos de sa&uacute;de&rdquo;, conclu&iacute;ram os pesquisadores.
</p>
</p>

{% endblock %}

templates/www/article3.html
{% extends "www/base.html" %}

{% block body_class %}articles{% endblock %}
{% block content %}
<h1>Fotos do Dr. Frank</h1>
<br/>
<br/>

<p align="justify"><div class="storytext">
<strong>O congresso da <a href="http://www.ifso.com/">IFSO</a> (International Federation for the Surgery of Obesity
and Metabolic Disorders) é a mais importante reunião anual dos especialistas
nesta área da medicina. Este ano, em sua 16ª edição, ele foi realizado em Hamburg,
Alemanha.</strong>
</div>

<br />
<p>
    Dr. Frank participou buscando a excelência no atendimento a seus pacientes. Marque uma <a alt="contato" href="/contact/">consulta</a> já.
</p>

</p>
<br />
<br />

<ul class="gallery"> 
    <li>
        <a href="#">
        <em style='left: 215px; top: 55px'></em>
        <img height="500" width="650" src="{{ MEDIA_URL }}img/congresso_alemanha.jpg" alt="Dr. Frank Arturo" /></a>
    </li>
</ul>


{% endblock %}

templates/www/articles.html
{% extends "www/base.html" %}

{% block body_class %}articles{% endblock %}
{% block content %}

<div id="content">
	<h1>Artigos</h1>
        <br/>
        <br/>
	<div>
		<div id="bmi-box">
			<a href="{% url www_article1 %}">Fazer dieta não reduz número de células de gordura, diz estudo</a>
		</div>
		<br/>
		<div id="bmi-box">
			<a href="{% url www_article2 %}">Metade da população mundial 'está obesa ou acima do peso</a>
		</div>
		<br/>
		<div id="bmi-box">
			<a href="{% url www_article3 %}">Participação do Dr. Frank Arturo no Congresso Mundial de Cirurgia Bariatrica e Metabólica</a>
		</div>
		<br/>
		<div id="bmi-box">
			<a href="{% url www_article4 %}">Participação do Dr. Frank Arturo no Congresso Sociedade Brasileira de Cirurgia Bariátrica e Metabólica</a>
		</div>
	</div>
</div>

{% endblock %}

templates/www/base.html
{% extends "base.html" %}
{% load i18n %}

{% block base_extra_head %}
    <script type="text/javascript" src="{{MEDIA_URL}}js/jquery.defaultvalue.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}js/jquery.colorbox-min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            //$.colorbox({href:'{{MEDIA_URL}}img/congresso_alemanha.jpg'});
            
            $('h2.accordion').css('cursor', 'pointer');
            $('div.accordion').css('display', 'none');
            
            $('h2.accordion').click(function(){
                $(this).next('div.accordion').slideToggle("slow");
            });
        });
    </script>
    
    <style type="text/css">
        #colorbox {
            position: absolute;
            height: 190px;
            width: 190px;
            z-index: 999;
        }
        
        .cboxPhoto {
            height: 500px;
            width: 600px;
        }
    </style>
{% endblock %}

{% block top %}
    <!-- <div class="search">
    <form method="get" action="http://www.google.com/search">
        <input type="text" name="q" id="search"/>
        <input type="hidden" name="sitesearch" value="frankarturo.com.br"/>
    </form> -->
    </div>
    <br class="clear"/>
    <ul id="nav">
        <li id="obesity"><a href="{% url www_obesity %}">{% trans "OBESITY" %}</a></li>
        <li id="team"><a href="{% url www_team %}">{% trans "EQUIPE" %}</a></li>
        <li id="bmi"><a href="{% url www_bmi %}">{% trans "CALCULAR IMC" %}</a></li>
        <li id="gallery"><a href="{% url www_photogallery %}">{% trans "Cirurgias" %}</a></li>
        <li id="articles"><a href="{% url www_articles %}">{% trans "ARTIGOS" %}</a></li>
        <li id="contact"><a href="{% url contact_form %}">{% trans "CONTATO" %}</a></li>
    </ul>
    
    <div class="divider-vertical">&nbsp;</div>
    
{% endblock %}

{% block footer %}
<div id="footer-wrapper">
    <ul id="footer-menu">
        <li><a href="/">Home</a></li>
        <!-- <li><a href="/sitemap.xml">Sitemap</a></li> -->
        <li><a href="{% url contact_form %}">Contato</a></li>
    </ul>    
</div>
    
<script type="text/javascript">
$(document).ready(function() {
    $("#search").defaultvalue(
        '{% trans "SEARCH" %}'
    );
});
</script>
{% endblock %}

{% block  base_body_end %}
{% endblock %}

templates/www/bmi.html
{% extends "www/base.html" %}
{% load i18n %}

{% block body_class %}bmi{% endblock %}

{% block content %}
<div id="bmi-box">
{% trans "IMC é o índice de massa corpórea. Isso é um padrão internacional para verificar se o indivíduo está no peso ideal." %}
</div>
    <br class="clear"/>
    <div class="horizontal-divider">&nbsp;</div>
    <form class='bmi' method="post">
        <div class="bmi-fields">
            <div>
            <label for="id_weight">{% trans "Peso" %}:</label>
                <input type="text" name="weight" id="id_weight" />
                {% trans "quilos." %}
            </div>
            
            <div>
            <label for="id_height">{% trans "Altura" %}:</label>
                <input type="text" name="height" id="id_height" />
                {% trans "metros." %}
            </div>
        </div>
            
        <input id='id_calculate' type='submit' value="{% trans 'Calcular' %}" class="submit" />
    </form>
    <br/>
    <br/>
    {% if bmi %}
        <div id="bmi-box" align="center">
            Fator IMC: {{ bmi|floatformat }}
        </div>
        <br/>
        <div id="bmi-box" align="center">
        {% if bmi < 25 %}
                {% trans "Peso Normal" %}
        {% endif %}
        
        {% if bmi >= 25 and bmi < 27 %}
                {% trans "Sobrepeso" %}
        {% endif %}
        
        {% if bmi >= 27 and bmi < 30 %}
            {% trans "Obesidade Leve" %}
        {% endif %}
        
        {% if bmi >= 30 and bmi < 35 %}
            {% trans "Obesidade Moderada" %}
        {% endif %}
        
        {% if bmi >= 35 and bmi < 40 %}
            {% trans "Obesidade Severa" %}
        {% endif %}
        
        {% if bmi >= 40 and bmi < 50 %}
            {% trans "Obesidade Mórbida" %}
        {% endif %}
        
        {% if bmi > 50 %}
                {% trans "Super Obesidade" %}
        {% endif %}
        </div>
    {% endif %}
{% endblock %}

{% block  base_body_end %}
    <script type="text/javascript" src="{{MEDIA_URL}}js/jquery.maskedinput-1.2.2.min.js"></script>
    <script type="text/javascript" src="{{MEDIA_URL}}js/jquery.alphanumeric.pack.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#id_weight').numeric({allow:"."});
            $('#id_height').mask("9.99");
        });
    </script>
{% endblock %}

templates/www/capella.html
{% extends "www/base.html" %}
{% load i18n %}

{% block body_class %}photogallery{% endblock %}

{% block extra_head %}
    <script src="{{ MEDIA_URL }}js/gallery/galleria.js"></script>
	
	<style>
        html,body{background:#FFFF}
			.content{color:#eee;font:14px/1.4 "helvetica neue", arial,sans-serif;width:620px;margin:20px auto}
        h1{line-height:1.1;letter-spacing:-1px;}
        a {color:#fff;}
        #galleria{height:400px;width:400px}
    </style>
{% endblock %}

{% block content %}
    <div id="content">
		<h1>Cirurgia de Capella</h1>
		<br/>
		<div id="galleria">
			<img src="{{ MEDIA_URL }}img/capella/capella1.png" alt="Pic 1" />
			<img src="{{ MEDIA_URL }}img/capella/capella2.png" alt="Pic 2" />
			<img src="{{ MEDIA_URL }}img/capella/capella3.png" alt="Pic 3" />
			<img src="{{ MEDIA_URL }}img/capella/capella4.png" alt="Pic 4" />
			<img src="{{ MEDIA_URL }}img/capella/capella5.png" alt="Pic 4" />
			<img src="{{ MEDIA_URL }}img/capella/capella6.png" alt="Pic 4" />
			<img src="{{ MEDIA_URL }}img/capella/capella7.png" alt="Pic 4" />
			<img src="{{ MEDIA_URL }}img/capella/capella8.png" alt="Pic 4" />
			<img src="{{ MEDIA_URL }}img/capella/capella9.png" alt="Pic 4" />
		</div>
	</div>
	<script>
		// Load the classic theme
		Galleria.loadTheme('../../static/js/gallery/galleria.classic.js');
		// Initialize Galleria
		$('#galleria').galleria();
    </script>
{% endblock %}

templates/www/index.html
{% extends "www/base.html" %}
{% load i18n %}

{% block content %}
<div id="slider" class="slider">
    <img src="{{MEDIA_URL}}img/frankarturo.png" height="200px" />
    <!--<div class="slider-photo"></div>
    <div class="slider"></div>
    <div class="slider-text"></div>-->
    
</div>

<div class="horizontal-divider">&nbsp;</div>

<div id="featured">
    <div class="column">
        <a class="more" href="{% url www_photogallery %}">
            <h2>Cirurgias</h2>
        </a>
        <a class="more" href="{% url www_photogallery %}">
            <img src="{{MEDIA_URL}}img/cirurgia_logo.jpg" alt="Testimonial" width="290px" height="80px" />
        </a>
        <p>
            Confira como funciona as cirurgias realizadas pelo Dr. Frank.
            <br/><br/>
            <a class="more" href="{% url www_photogallery %}">Ver Mais...</a>
        </p>
    </div>
    
    <div class="column">
        <a class="more" href="{% url www_articles %}">
            <h2>{% trans "Last Articles" %}</h2>
        </a>
        <a class="more" href="{% url www_articles %}">
            <img src="{{MEDIA_URL}}img/last_articles.jpg" alt="{% trans 'Last Articles' %}"/>
        </a>
        <ul class="left">
            {% for article in last_articles %}
                {% if forloop.counter <= 3 %}
                    <a href="{{ article.get_absolute_url }}">
                        <li>{{article.title}}</li>
                    </a>
                {% endif %}
            {% endfor %}
        </ul>
        
        <ul class="right">
            {% for article in last_articles %}
                {% if forloop.counter > 3 %}
                    <a href="{{ article.get_absolute_url }}">
                        <li>{{article.title}}</li>
                    </a>
                {% endif %}
            {% endfor %}
            <li><a class="more" href="{% url www_articles %}">{% trans "And more..." %}</a></li>
        </ul>
    </div>
    
    <div class="column">
        <h2>{% trans 'Where are we' %}</h2>
        <img src="{{MEDIA_URL}}img/logo_local.jpg" alt="{% trans 'Where are we' %}" width="290px" height="80px"/>
        <p>
            <b>Harmony Medical Center</b><br/>
            Avenida Dom Luiz, 1233, Sala 312 - Meireles<br/>
            Fortaleza - CE, 60160-230, Brasil<br/>
            Telefone: (85) 3486-6124<br/>
            Celular: (85) 9136-2422 / 9693-7952<br/>
            Email: <a href="{% url contact_form %}">frankcasallo@yahoo.com.br</a>
        </p>
    </div>
</div>
{% endblock %}

templates/www/team.html
{% extends "www/base.html" %}
{% load i18n %}

{% block body_class %}team{% endblock %}

{% block content %}
    <div id="equipe" style="float: left">
        <h1>{% trans "Equipe" %}</h1>
        <br/>
        <p>Dr. HENRIQUE MACAMBIRA CRM 4686</p>
        <p>Dr. GLAUCIO NÓBREGA CRM 4049</p>
        <p>Dr. JAIME SALES CRM 3675</p>
        <p>Dr. FRANK ARTURO CRM 8889</p>
    </div>
    <br/>
    <br/>
    <div id="fotos">
        <img src="{{ MEDIA_URL }}img/cito_logo.png"/>
        <img src="{{ MEDIA_URL }}img/team2.jpg" width="600px" height="400px" />
    </div>
{% endblock %}

templates/www/tips.html
{% extends "www/base.html" %}

{% block body_class %}tips{% endblock %}

{% block content %}
{% endblock %}